displayName: abtest
type: middleware
import: github.com/unnoo/abtest
summary: a traefik plugin for abtest
iconPath:
bannerPath:

testData:
  serviceName: "api"
  redisAddr: "127.0.0.1:6379"
  redisPassword: ""
  redisEnable: false
  redisLoadInterval: 10
  userIdentifyPrefix: ""
  headerAccessToken: "Authorization"
  queryAccessToken: "access_token"
  cookieAccessToken: "access_token"
  headerVersion: "X-Version"
  redisRulesKey: "abtests"
  redisMaxRuleLen: 256
  urlRuleMatchKey: "abtest_env"
  rules:
    - name: "rule1"
      serviceName: "api"
      enable: true
      desc: "desc"
      priority: 2
      Hosts:
        - http://localhost:8999/r1/beta
        - http://localhost:8999/r1/alpha
        - http://localhost:8999/r1/test
      stratege: match_url
      list:
        - 1
        - 3
      percent: 10
      minVersion: "1.1.1"
      maxversion: "2.2.2"
