version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--pilot.token=bb77a90c-fed6-48e2-a6ff-1a3a71239a8e"
      - "--experimental.plugins.block.modulename=github.com/traefik/plugin-blockpath"
      - "--experimental.devPlugin."
    ports:
      - "80:80"
      - "18080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".:/plugin"

  whoami1:
    image: "traefik/whoami"
    container_name: "whoami1"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami1.rule=Host(`whoami1.localhost`)"
      - "traefik.http.routers.whoami1.entrypoints=web"
  whoami2:
    image: "traefik/whoami"
    container_name: "whoami2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami2.rule=Host(`whoami2.localhost`)"
      - "traefik.http.routers.whoami2.entrypoints=web"
